Adding home compponent and placeholders
alkemyTech/OT191-angular pull request #11
Opened 2022-04-19 14:52 UTC by stefanoracke

Al final separe las actividades es la de agregar el Home con el titulo que despues viene el endpoint y los placeholders para las novedades y el slider

2022-04-21 03:50 UTC, anagon88 requested changes
Adjuntar screen de la pantalla

2022-04-21 15:52 UTC, stefanoracke commented
![image](https://user-images.githubusercontent.com/80729784/164500760-99fdbb80-7ee4-47e8-b8c8-0c6389c88380.png)

Agregando la sreen

2022-04-22 02:18 UTC, anagon88 requested changes
fijate que tiene que coincidir con este diseño 
https://www.figma.com/file/sjpq9FnkPbPNO3cnqkiXGM/Caso-ONG-Alkemy?node-id=0%3A1

2022-04-25 18:07 UTC, stefanoracke commented
![image](https://user-images.githubusercontent.com/80729784/165148152-4f2ee50a-579a-4c32-80c4-a2098a00f92b.png)

2022-04-25 22:11 UTC, anagon88 approved these changes

2022-04-26 00:10 UTC, merged