Ot191 30
alkemyTech/OT191-angular pull request #13
Opened 2022-04-19 22:11 UTC by stefanoracke

Al final separe las actividades es la de agregar el Home con el titulo que despues viene el endpoint y los placeholders para las novedades y el slider

2022-04-21 03:59 UTC, anagon88 requested changes

2022-04-21 03:59 UTC, anagon88 commented on src/app/features/backoffice/pages/slides/slides.component.ts
> +  public slide:SlideI = {
elimimar el mock, no subirlo

2022-04-21 03:59 UTC, anagon88 commented on src/app/features/backoffice/pages/slides/slides.component.ts
> +    console.log(this.stringimage)
eliminar console logs

2022-04-21 03:59 UTC, anagon88 commented on src/app/features/features.module.ts
> -    ActivityFormComponent,
esta bien eliminar estos o fue un problema de mergeo?

2022-04-26 00:40 UTC, stefanoracke commented on src/app/features/backoffice/pages/slides/slides.component.ts
> +  public slide:SlideI = {
hecho

2022-04-26 00:41 UTC, stefanoracke commented on src/app/features/backoffice/pages/slides/slides.component.ts
> +    console.log(this.stringimage)
eliminados

2022-04-26 13:59 UTC, anagon88 approved these changes

2022-04-26 13:59 UTC, merged