Ot191 33
alkemyTech/OT191-angular pull request #15
Opened 2022-04-20 02:43 UTC by stefanoracke

2022-04-21 04:05 UTC, anagon88 requested changes

2022-04-21 04:05 UTC, anagon88 commented on src/app/features/backoffice/pages/userform/userform.component.html
> +<body>
no hace falta el tag body y header

2022-04-26 00:34 UTC, stefanoracke commented on src/app/features/backoffice/pages/userform/userform.component.html
> +<body>
Hecho

2022-04-26 14:00 UTC, anagon88 approved these changes

2022-04-26 15:31 UTC, merged