Fixes
alkemyTech/OT191-angular pull request #30
Opened 2022-04-26 22:11 UTC by Daniel-Mdn

added title component in:
* activity component
* category component
* edit-organization component
* principal component

2022-04-28 02:55 UTC, anagon88 requested changes

2022-04-28 02:55 UTC, anagon88 commented on src/app/features/backoffice/activities-list/activities-list.component.ts
> +			{
borrar datos mockeados

2022-04-28 02:55 UTC, anagon88 commented on src/app/features/backoffice/activities/activities.component.ts
> +			created_at: "2022-04-16",
borrar datos mockeados

2022-04-28 02:55 UTC, anagon88 commented on src/app/features/backoffice/categories/categories.component.html
> +					? 'mb-4'
formatear documento con el prettier

2022-04-28 14:11 UTC, Daniel-Mdn commented on src/app/features/backoffice/categories/categories.component.html
> +					? 'mb-4'
Ya use el prettier y no realiza cambios.

2022-04-29 22:48 UTC, anagon88 approved these changes

2022-05-02 18:02 UTC, merged