Ot191 76
alkemyTech/OT191-angular pull request #31
Opened 2022-04-26 22:21 UTC by Javernaver

- Se crea el servicio para las peticiones de novedades
- Se prepara el modulo auth para cuando las peticiones a auth funcionen
- Se ajusta el formulario de edicion Home para ajustarse a el estandar y se agrega el titulo

2022-04-28 03:00 UTC, anagon88 requested changes

2022-04-28 03:00 UTC, anagon88 commented on src/app/features/backoffice/components/table-users/table-users.component.html
> +      [style]="{ width: '100px', height: '100px' }"
mover a la hoja de estilos

2022-04-28 03:00 UTC, anagon88 commented on src/app/features/backoffice/components/table-users/table-users.component.ts
> +    console.log(this.user);
eliminar console.log

2022-04-29 22:49 UTC, anagon88 requested changes

2022-04-29 22:49 UTC, anagon88 commented on src/app/features/backoffice/components/table-users/table-users.component.ts
> +    console.log(this.user);
eliminar la linea 54

2022-04-29 23:01 UTC, Javernaver commented
listo

2022-04-29 23:03 UTC, anagon88 approved these changes

2022-04-29 23:03 UTC, merged