Ot191 64
alkemyTech/OT191-angular pull request #37
Opened 2022-05-01 02:07 UTC by stefanoracke

Creadas la tabla de slides, y cambiado los formularios

2022-05-02 17:34 UTC, anagon88 requested changes

2022-05-02 17:34 UTC, anagon88 commented on src/app/features/backoffice/components/slides-table/slides-table.component.ts
> +  stylesDialog = { width: '400px', height: '500px' };
pasarlo a la hoja de estilos

2022-05-02 17:34 UTC, anagon88 commented on src/app/features/backoffice/components/slides-table/slides-table.component.ts
> +            detail: "Se han eliminado los usuarios",
esta bien este texto?

2022-05-02 17:34 UTC, anagon88 commented on src/app/features/backoffice/components/slides-table/slides-table.component.ts
> +        "¿Seguro que quieres borrar este usuario?",
esta bien este texto?

2022-05-02 20:10 UTC, stefanoracke commented
Cambios Hehcos

2022-05-02 20:10 UTC, stefanoracke commented
Cambios realizados

2022-05-03 18:53 UTC, anagon88 approved these changes

2022-05-03 18:53 UTC, merged