Ot191 104
alkemyTech/OT191-angular pull request #42
Opened 2022-05-03 14:22 UTC by Daniel-Mdn

* Added error section with the dialog component for requests in activities-list component and activity component.
![image](https://user-images.githubusercontent.com/62775588/166471028-6ff31eeb-67d4-4b2a-b699-149325fcbbf2.png)

2022-05-07 02:57 UTC, anagon88 requested changes

2022-05-07 02:57 UTC, anagon88 commented on src/app/features/backoffice/activities-list/activities-list.component.ts
> +				//------ Parte para eliminar del servidor  -----------
que seria este codigo comentado 2 veces?

2022-05-09 18:30 UTC, Daniel-Mdn commented on src/app/features/backoffice/activities-list/activities-list.component.ts
> +				//------ Parte para eliminar del servidor  -----------
era para evitar eliminar las actividades del servidor. Igual ese código ya la saque en la tarea 108 asi que ahora lo saco de esta tarea.

2022-05-10 00:44 UTC, anagon88 approved these changes

2022-05-10 00:44 UTC, merged