OT191-126,127
alkemyTech/OT191-angular pull request #49
Opened 2022-05-11 16:54 UTC by stefanoracke

Agregue el footer y el header en el mismo pull request

2022-05-12 23:24 UTC, anagon88 requested changes

2022-05-12 23:24 UTC, anagon88 commented on src/app/shared/components/footer/footer.component.ts
> +    console.log(respuesta)
borrar el console log

2022-05-12 23:24 UTC, anagon88 commented on src/app/shared/components/footer/footer.component.ts
> +    await this.OrgService.getOrganization().toPromise().then((response) => {
es necesario hacer el topromise?

2022-05-12 23:24 UTC, anagon88 commented on src/app/shared/components/navbar/navbar.component.ts
> +    console.log(this.routerList);
borrar

2022-05-12 23:25 UTC, anagon88 commented
falta la imagen

2022-05-16 20:34 UTC, anagon88 requested changes

2022-05-16 20:34 UTC, anagon88 commented on src/app/features/auth/effects/auth.effects.ts
> +  // statelogged$ = createEffect(()=>this.actions$.pipe(ofType<StateLogin>(AuthActionTypes.)))
eliminar comentado

2022-05-16 20:34 UTC, anagon88 commented on src/app/shared/components/footer/footer.component.html
> +    <!-- <div #org="dataOrg$ | async">
aliminar codigo comentado

2022-05-17 14:20 UTC, stefanoracke commented on src/app/shared/components/footer/footer.component.html
> +    <!-- <div #org="dataOrg$ | async">
codigo comentado eliminado

2022-05-18 13:08 UTC, anagon88 approved these changes

2022-05-18 16:06 UTC, merged