Ot191 25
alkemyTech/OT191-angular pull request #8
Opened 2022-04-19 00:06 UTC by Javernaver

- Mismos elementos de Ot191 26
- Servicio de validacion para match de contraseñas, patrones de email y los requisitos de caracteres de contraseña
- Formulario y pantalla de registro

![image](https://user-images.githubusercontent.com/38194420/163895353-a538f5d7-5818-4d72-bc7d-298a3454eca4.png)

2022-04-20 15:13 UTC, anagon88 requested changes

2022-04-20 15:13 UTC, anagon88 commented on src/app/features/auth/pages/login-form/login-form.component.html
> +                      [style]="{ height: '3px' }"
moverlo a la hoja de estilos

2022-04-20 15:13 UTC, anagon88 commented on src/app/features/auth/pages/login-form/login-form.component.ts
> +      //console.log(user);
eloiminar codigo comentado

2022-04-20 15:13 UTC, anagon88 commented on src/app/features/auth/pages/register-form/register-form.component.html
> +                      [style]="{ height: '3px' }"
mover hoja de estilos

2022-04-20 15:13 UTC, anagon88 commented on src/app/features/auth/pages/register-form/register-form.component.ts
> +      //console.log(user);
eliminar codigo comentado

2022-04-20 15:13 UTC, anagon88 commented on src/app/features/auth/pages/register-form/register-form.component.ts
> +import { Component } from '@angular/core';
formatear con prettier el documento

2022-04-20 21:21 UTC, Javernaver commented
correcciones hechas

2022-04-21 03:42 UTC, anagon88 approved these changes

2022-04-21 03:42 UTC, merged